## Model Training

## RandomForestClassifier

In [1]:
import pandas as pd
import os
import joblib
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    confusion_matrix
)

In [2]:
X_train_scaled = np.load(os.path.join("scaled", "X_train_scaled.npy"))
X_val_scaled = np.load(os.path.join("scaled", "X_val_scaled.npy"))
X_test_scaled = np.load(os.path.join("scaled", "X_test_scaled.npy"))
y_train = np.load(os.path.join("scaled", "y_train.npy"))
y_val = np.load(os.path.join("scaled", "y_val.npy"))
y_test = np.load(os.path.join("scaled", "y_test.npy"))

scaler = joblib.load(os.path.join("scaled", "fitted_scaler.pkl"))
print("Data load Successfully")

Data load Successfully


In [3]:
rf_model=RandomForestClassifier(n_estimators=100,max_depth=None,random_state=42,n_jobs=-1,class_weight='balanced')
rf_model.fit(X_train_scaled,y_train)

,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstrap: bool, default=TrueWhether bootstrap samples are used when building trees. If False, thewhole dataset is used to build each tree.",True
,"oob_score oob_score: bool or callable, default=FalseWhether to use out-of-bag samples to estimate the generalization score.By default, :func:`~sklearn.metrics.accuracy_score` is used.Provide a callable with signature `metric

In [4]:
y_val_pred = rf_model.predict(X_val_scaled)
y_val_prob = rf_model.predict_proba(X_val_scaled)[:, 1]

In [5]:
print("=" * 70)
print("RANDOM FOREST - VALIDATION RESULTS")
print("=" * 70)

print("Accuracy :", accuracy_score(y_val, y_val_pred))
print("Precision:", precision_score(y_val, y_val_pred, zero_division=0))
print("Recall   :", recall_score(y_val, y_val_pred, zero_division=0))
print("F1 Score :", f1_score(y_val, y_val_pred, zero_division=0))
print("ROC-AUC  :", roc_auc_score(y_val, y_val_prob))

print("\nClassification Report:")
print(classification_report(y_val, y_val_pred, zero_division=0))

print("\nConfusion Matrix:")
print(confusion_matrix(y_val, y_val_pred))

RANDOM FOREST - VALIDATION RESULTS
Accuracy : 0.9834167629315878
Precision: 0.4532541869832521
Recall   : 0.9976668222118525
F1 Score : 0.6233236151603498
ROC-AUC  : 0.9996658987546074

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.98      0.99    307354
           1       0.45      1.00      0.62      4286

    accuracy                           0.98    311640
   macro avg       0.73      0.99      0.81    311640
weighted avg       0.99      0.98      0.99    311640


Confusion Matrix:
[[302196   5158]
 [    10   4276]]


In [6]:
# Test

y_test_pred = rf_model.predict(X_test_scaled)
y_test_prob = rf_model.predict_proba(X_test_scaled)[:, 1]

print("\n" + "=" * 70)
print("RANDOM FOREST - TEST RESULTS")
print("=" * 70)

print("Accuracy :", accuracy_score(y_test, y_test_pred))
print("Precision:", precision_score(y_test, y_test_pred, zero_division=0))
print("Recall   :", recall_score(y_test, y_test_pred, zero_division=0))
print("F1 Score :", f1_score(y_test, y_test_pred, zero_division=0))
print("ROC-AUC  :", roc_auc_score(y_test, y_test_prob))

print("\nClassification Report:")
print(classification_report(y_test, y_test_pred, zero_division=0))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))


RANDOM FOREST - TEST RESULTS
Accuracy : 0.9834167629315878
Precision: 0.4532541869832521
Recall   : 0.9976668222118525
F1 Score : 0.6233236151603498
ROC-AUC  : 0.9996658987546074

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.98      0.99    461031
           1       0.45      1.00      0.62      6429

    accuracy                           0.98    467460
   macro avg       0.73      0.99      0.81    467460
weighted avg       0.99      0.98      0.99    467460


Confusion Matrix:
[[453294   7737]
 [    15   6414]]


In [7]:
import pandas as pd

# 1. Model se feature importances lein
importances = rf_model.feature_importances_

# 2. Agar scaler save karte waqt feature names save hue the:
if hasattr(scaler, 'feature_names_in_'):
    feature_names = scaler.feature_names_in_
else:
    # Agar names nahi hain, to hum generic names (Feature_0, Feature_1) de dete hain
    feature_names = [f"Feature_{i}" for i in range(len(importances))]

# DataFrame banayein
df_importance = pd.DataFrame({'Feature': feature_names, 'Importance': importances})
df_importance = df_importance.sort_values(by='Importance', ascending=False)

# Top 10 features print karein
print("Top 10 Most Important Features:")
print(df_importance.head(10))


Top 10 Most Important Features:
                     Feature  Importance
36         Packet Length Max    0.087945
48           Avg Packet Size    0.084140
49      Avg Fwd Segment Size    0.075430
37        Packet Length Mean    0.068540
8     Fwd Packet Length Mean    0.067090
4   Fwd Packets Length Total    0.052141
52         Subflow Fwd Bytes    0.052084
6      Fwd Packet Length Max    0.050524
24               Fwd IAT Min    0.048834
54         Subflow Bwd Bytes    0.031393


##  IsolationForest

In [8]:
from sklearn.ensemble import IsolationForest
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

# Isolation Forest

iso_model = IsolationForest(
    n_estimators=100,
    contamination="auto",
    random_state=42,
    n_jobs=-1
)

iso_model.fit(X_train_scaled)


,"n_estimators n_estimators: int, default=100The number of base estimators in the ensemble.",100
,"max_samples max_samples: ""auto"", int or float, default=""auto""The number of samples to draw from X to train each base estimator.- If int, then draw `max_samples` samples.- If float, then draw `max_samples * X.shape[0]` samples.- If ""auto"", then `max_samples=min(256, n_samples)`.If max_samples is larger than the number of samples provided,all samples will be used for all trees (no sampling).",'auto'
,"contamination contamination: 'auto' or float, default='auto'The amount of contamination of the data set, i.e. the proportionof outliers in the data set. Used when fitting to define the thresholdon the scores of the samples.- If 'auto', the threshold is determined as in the original paper.- If float, the contamination should be in the range (0, 0.5]... versionchanged:: 0.22 The default value of ``contamination`` changed from 0.1 to ``'auto'``.",'auto'
,"max_features max_features: int or float, default=1.0The number of features to draw from X to train each base estimator.- If int, then draw `max_features` features.- If float, then draw `max(1, int(max_features * n_features_in_))` features.Note: using a float number less than 1.0 or integer less than number offeatures will enable feature subsampling and leads to a longer runtime.",1.0
,"bootstrap bootstrap: bool, default=FalseIf True, individual trees are fit on random subsets of the trainingdata sampled with replacement. If False, sampling without replacementis performed.",False
,"n_jobs n_jobs: int, default=NoneThe number of jobs to run in parallel for :meth:`fit`. ``None`` means 1unless in a :obj:`joblib.parallel_backend` context. ``-1`` means usingall processors. See :term:`Glossary ` for more details.",-1
,"random_state random_state: int, RandomState instance or None, default=NoneControls the pseudo-randomness of the selection of the featureand split values for each branching step and each tree in the forest.Pass an int for reproducible results across multiple function calls.See :term:`Glossary `.",42
,"verbose verbose: int, default=0Controls the verbosity of the tree building process.",0
,"warm_start warm_start: bool, default=FalseWhen set to ``True``, reuse the solution of the previous call to fitand add more estimators to the ensemble, otherwise, just fit a wholenew forest. See :term:`the Glossary `... versionadded:: 0.21",False


In [9]:
# Validation

y_val_iso = iso_model.predict(X_val_scaled)

# Isolation Forest:
# +1 = Normal
# -1 = Anomaly
y_val_anomaly = (y_val_iso == -1).astype(int)

print("=" * 70)
print("ISOLATION FOREST - VALIDATION RESULTS")
print("=" * 70)

print("\nClassification Report:")
print(classification_report(
    y_val,
    y_val_anomaly,
    zero_division=0
))

print("\nConfusion Matrix:")
print(confusion_matrix(y_val, y_val_anomaly))




ISOLATION FOREST - VALIDATION RESULTS

Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.92      0.95    307354
           1       0.01      0.04      0.01      4286

    accuracy                           0.90    311640
   macro avg       0.50      0.48      0.48    311640
weighted avg       0.97      0.90      0.94    311640


Confusion Matrix:
[[281686  25668]
 [  4104    182]]


In [10]:

# Test

y_test_iso = iso_model.predict(X_test_scaled)

y_test_anomaly = (y_test_iso == -1).astype(int)

print("\n" + "=" * 70)
print("ISOLATION FOREST - TEST RESULTS")
print("=" * 70)

print("\nClassification Report:")
print(classification_report(
    y_test,
    y_test_anomaly,
    zero_division=0
))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_test_anomaly))



# Anomaly Scores


val_anomaly_score = -iso_model.score_samples(X_val_scaled)
test_anomaly_score = -iso_model.score_samples(X_test_scaled)

print("\n" + "=" * 70)
print("ANOMALY SCORES")
print("=" * 70)

print("Validation score range:",
      val_anomaly_score.min(),
      "to",
      val_anomaly_score.max())

print("Test score range:",
      test_anomaly_score.min(),
      "to",
      test_anomaly_score.max())


ISOLATION FOREST - TEST RESULTS

Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.92      0.95    461031
           1       0.01      0.04      0.01      6429

    accuracy                           0.90    467460
   macro avg       0.50      0.48      0.48    467460
weighted avg       0.97      0.90      0.94    467460


Confusion Matrix:
[[422529  38502]
 [  6156    273]]

ANOMALY SCORES
Validation score range: 0.31924224083078345 to 0.7706771528566296
Test score range: 0.31924224083078345 to 0.7706771528566296


## HYBRID RISK SCORE

In [11]:
# NORMALIZE ISOLATION FOREST SCORES


val_iso_min = val_anomaly_score.min()
val_iso_max = val_anomaly_score.max()

# Min-Max Scaling Formula: (Score - Min) / (Max - Min)
val_iso_norm = (
    (val_anomaly_score - val_iso_min)
    / (val_iso_max - val_iso_min + 1e-10)
)

test_iso_norm = (
    (test_anomaly_score - val_iso_min)
    / (val_iso_max - val_iso_min + 1e-10)
)

# Keep test values within 0-1
test_iso_norm = np.clip(test_iso_norm, 0, 1)


# HYBRID RISK SCORE

alpha = 0.5

val_hybrid_risk = (
    alpha * y_val_prob
    +
    (1 - alpha) * val_iso_norm
)

test_hybrid_risk = (
    alpha * y_test_prob
    +
    (1 - alpha) * test_iso_norm
)


# CHECK RESULTS

print("=" * 70)
print("HYBRID RISK SCORE COMPLETED")
print("=" * 70)

print("\nValidation Hybrid Risk:")
print("Min :", val_hybrid_risk.min())
print("Max :", val_hybrid_risk.max())
print("Mean:", val_hybrid_risk.mean())

print("\nTest Hybrid Risk:")
print("Min :", test_hybrid_risk.min())
print("Max :", test_hybrid_risk.max())
print("Mean:", test_hybrid_risk.mean())

print("\nFirst 10 Test Hybrid Scores:")
print(test_hybrid_risk[:10])

HYBRID RISK SCORE COMPLETED

Validation Hybrid Risk:
Min : 0.0
Max : 0.9050058352567704
Mean: 0.07867089919561861

Test Hybrid Risk:
Min : 0.0
Max : 0.9050058352567704
Mean: 0.0786708991956186

First 10 Test Hybrid Scores:
[0.31761716 0.31199139 0.29946292 0.17975439 0.0100915  0.00666303
 0.05535922 0.35117589 0.00677405 0.00603863]


In [14]:
os.makedirs("models",exist_ok=True)
#Save both Model in models folder
joblib.dump(rf_model,os.path.join("models","Supervised_rf_model.pkl"))
joblib.dump(iso_model,os.path.join("models","unsupervised_iso_model.pkl"))

#Hybrid score save in scaled folder
np.save(os.path.join("scaled", "val_hybrid_risk.npy"), val_hybrid_risk)
np.save(os.path.join("scaled", "test_hybrid_risk.npy"), test_hybrid_risk)


print("-> Clean Structure Saved successfully!")
print("-> Models saved in: models/ folder.")
print("-> Data arrays saved in: scaled/ folder.")

-> Clean Structure Saved successfully!
-> Models saved in: models/ folder.
-> Data arrays saved in: scaled/ folder.
